import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useRef } from 'react'
import profile from "../../public/images/profile/last.png"
import { useInView, useMotionValue, useSpring } from 'framer-motion'
import Sckil from '@/components/Sckil'
import Expreneces from '@/components/Expreneces'
import Education from '@/components/Education'
import TransjationEffact from '@/components/TransjationEffact'
import Skills from '@/components/Skills'


const AnimitedNumber = ({value})=>{
  const ref = useRef(null)
  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue,{duration:3000});
  const isInvalue = useInView(ref,{once:true});

  useEffect(()=>{
    if(isInvalue){
      motionValue.set(value)
    }
  },[isInvalue,motionValue,value])

  useEffect(()=>{
    springValue.on("change",(latest)=>{
      if(ref.current && latest.toFixed(0) <= value){
        ref.current.textContent = latest.toFixed(0);
      }
    })
  },[springValue,value])

  return <span ref={ref}></span>

}



const About = () => {
  return (
    <>
        <Head>
        <title>profile || About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransjationEffact/>
      <main className='flex flex-col w-full items-center justify-center'>
        <Layout className='pt-5 md:pt-16'> 
            <AnimatedText text={"About Me "} className='mb-8 md:mb-16 !text-3xl sm:!text-4xl lg:!text-6xl'/>
            <div className=' hidden sm:grid w-full grid-cols-8 gap-16 dark:text-light'>
                <div className='col-span-8 order-1 sm:order-0 lg:col-span-3  sm:col-span-4 flex flex-col items-start justify-start'>
                    <h2 className='text-lg font-bold mb-4 uppercase text-dark/75 dark:text-light'>Biography</h2>
                    <p className=' font-medium w-full'>
                    Hi! I'm Dikash Chandra , a passionate MERN-stack developer. I develop websites using MERN technology. I literally spend 8-10 hours every day on Programming and Problem Solving. Programming is my love and passionate. My core skill is based on JavaScript and I love to do most of the things using JavaScript. I love to make the web more open to the world.
                    </p>
                    
                    <p className=' font-medium py-4'>
                    - I believe that design is about more than just making things look pretty – it's about solving problems and 
                    creating intuitive, enjoyable experiences for users. 
                    </p>

                    <p className=' font-medium'>
                    - Whether I'm working on a website, mobile app, or 
                    other digital product, I bring my commitment to design excellence and user-centered thinking to 
                    every project I work on. I look forward to the opportunity to bring my skills and passion to your next project.
                    </p>
                </div> 

                <div className=' sm:order-1 col-span-8 lg:col-span-3 sm:col-span-4 bg-light border-2 border-solid border-dark dark:bg-dark dark:border-light rounded-2xl h-max p-8 relative order-2'>
                    <div className=' absolute top-0 -right-3 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light -z-10'/>
                    <Image src={profile} alt='profile' className='w-full h-auto rounded-2xl'/>
                </div>

                <div className='col-span-8 w-full lg:col-span-2 flex lg:flex-col justify-between items-end order-3'>
                    <div className='flex flex-col items-end justify-center'>
                      <span className=' text-3xl sm:text-4xl lg:text-7xl font-bold inline-block'><AnimitedNumber value={9}/>+</span>
                      <h2 className='sm:text-xl text-base font-medium text-dark/75 dark:text-light'>Satisfied Client</h2>
                    </div>
                    <div className='flex flex-col items-end justify-center'>
                      <span className=' text-3xl sm:text-4xl lg:text-7xl font-bold inline-block'><AnimitedNumber value={9}/>+</span>
                      <h2 className='sm:text-xl text-base font-medium text-dark/75 dark:text-light'>Projects Completed</h2>
                    </div>
                    <div className='flex flex-col items-end justify-center'>
                      <span className=' text-3xl sm:text-4xl lg:text-7xl font-bold inline-block'><AnimitedNumber value={2}/>+</span>
                      <h2 className='sm:text-xl text-base font-medium text-dark/75 dark:text-light'>Yeras Of Experience</h2>
                    </div>
                </div>
            </div>
            <div className='flex flex-col sm:hidden gap-10 dark:text-light'>

                <div className=' col-span-8 lg:col-span-3 sm:col-span-4 bg-light border-2 border-solid border-dark dark:bg-dark dark:border-light rounded-2xl h-max p-8 relative'>
                    <div className=' absolute top-0 -right-3 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light -z-10'/>
                    <Image src={profile} alt='profile' className='w-full h-auto rounded-2xl'/>
                </div>

                <div className=' sm:order-0 lg:col-span-3  sm:col-span-4 flex flex-col items-start justify-start'>
                    <h2 className='text-lg font-bold mb-4 uppercase text-dark/75 dark:text-light'>Biography</h2>
                    <p className=' font-medium w-full'>
                    Hi! I'm Dikash Chandra , a passionate MERN-stack developer. I develop websites using MERN technology. I literally spend 8-10 hours every day on Programming and Problem Solving. Programming is my love and passionate. My core skill is based on JavaScript and I love to do most of the things using JavaScript. I love to make the web more open to the world.
                    </p>
                    
                    <p className=' font-medium py-4'>
                    - I believe that design is about more than just making things look pretty – it's about solving problems and 
                    creating intuitive, enjoyable experiences for users. 
                    </p>

                    <p className=' font-medium'>
                    - Whether I'm working on a website, mobile app, or 
                    other digital product, I bring my commitment to design excellence and user-centered thinking to 
                    every project I work on. I look forward to the opportunity to bring my skills and passion to your next project.
                    </p>
                </div> 

                <div className='col-span-8 w-full lg:col-span-2 flex lg:flex-col justify-between items-end order-3'>
                    <div className='flex flex-col items-center justify-center'>
                      <span className=' text-3xl sm:text-4xl lg:text-7xl font-bold inline-block'><AnimitedNumber value={9}/>+</span>
                      <h2 className='sm:text-xl text-base font-medium text-dark/75 dark:text-light'>Satisfied Client</h2>
                    </div>
                    <div className='flex flex-col items-center  justify-center'>
                      <span className=' text-3xl sm:text-4xl lg:text-7xl font-bold inline-block'><AnimitedNumber value={9}/>+</span>
                      <h2 className='sm:text-xl text-base font-medium text-dark/75 dark:text-light'>Projects Completed</h2>
                    </div>
                    <div className='flex flex-col items-center  justify-center'>
                      <span className=' text-3xl sm:text-4xl lg:text-7xl font-bold inline-block'><AnimitedNumber value={2}/>+</span>
                      <h2 className='sm:text-xl text-base font-medium text-dark/75 dark:text-light'>Yeras Of Experience</h2>
                    </div>
                </div>
            </div>
             
            <Expreneces/>
            <Skills />
            {/* <Education/> */}
            <Sckil/>
        </Layout>
      </main>
    </>
  )
}

export default About