import Layout from '@/components/Layout'
import Head from 'next/head'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import HireMe from '@/components/HireMe'
import Light from "../../public/images/svgs/miscellaneous_icons_1.svg"
import { LinkArrow } from '@/components/Icons'
import TransjationEffact from '@/components/TransjationEffact'


export default function Home() {
  return (
    <>
      <Head>
        <title>profile || Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransjationEffact/>
      <main className='flex items-center text-dark w-full relative min-h-screen dark:text-light'>
        <Layout className='pt-0 '>
          <div className='flex items-center flex-col md:flex-row justify-between w-full'>
            <div className='w-full md:w-1/2'>
              <Image src={profilePic} alt='profile' className='w-full h-auto'/>
            </div>
            <div className='w-full md:w-1/2 flex flex-col items-center self-center'>
                <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-3xl sm:!text-4xl lg:!text-6xl  !text-left'/>
                <p className='my-4 font-medium text-base'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
                </p>
                <div className='flex items-center gap-3 self-start'>
                  <Link href={"/"} className='py-3 px-6 bg-dark dark:bg-light dark:text-dark text-light rounded-xl border-2 border-dark font-bold md:text-2xl text-xl flex hover:bg-light hover:text-dark transition-all duration-300 items-center'>Ruseme <LinkArrow className={"w-8"}/></Link>
                  <h3 className=' text-2xl font-medium underline'>Contact</h3>
                </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className=' absolute md:bottom-4 bottom-1 right-1 md:right-4 w-24 inline-block'>
          <Image src={Light} alt='light' className='w-20 h-20 md:w-full md:h-auto'/>
        </div>
      </main>
    </>
  )
}
