import Layout from '@/components/Layout'
import Head from 'next/head'
import profilePic from "../../public/images/profile/bikash.png"
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import HireMe from '@/components/HireMe'
import Light from "../../public/images/svgs/miscellaneous_icons_1.svg"
import { LinkArrow } from '@/components/Icons'
import TransjationEffact from '@/components/TransjationEffact'
import { useTypewriter, Cursor } from "react-simple-typewriter";
import Media from '@/components/Media'


export default function Home() {
  const [text] = useTypewriter({
    words: ["Professional Coder.", "MERN Stack Developer.", "UI Designer."],
    loop: true,
    typeSpeed: 20,
    deleteSpeed: 10,
    delaySpeed: 2000,
  });
  return (
    <>
      <Head>
        <title>profile || Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransjationEffact/>
      <main className='flex items-center text-dark w-full lg:-mt-16 relative min-h-screen dark:text-light'>
        <Layout className='pt-0 '>
          <div className='flex items-center flex-col gap-5 md:flex-row justify-between w-full'>
            <div className='w-full md:w-1/2 bacjground_image'>

            </div>
            <div className="w-full md:w-1/2 flex flex-col gap-20">
              <div className="flex flex-col gap-5">
                <h4 className=" text-lg font-medium">WELCOME TO MY WORLD</h4>
                <h1 className="text-3xl md:text-6xl font-bold text-dark dark:text-light">
                  Hi, I'm <span className="text-designColor capitalize">Bikash Chandra</span>
                </h1>
                <h2 className="text-2xl md:text-4xl font-bold text-dark dark:text-light">
                  a <span>{text}</span>
                  <Cursor
                    cursorBlinking="false"
                    cursorStyle="|"
                    cursorColor="#ff014f"
                  />
                </h2>
                <p className="text-base leading-6 tracking-wide">
                  I use animation as a third dimension by which to simplify experiences
                  and kuiding thro each and every interaction. I'm not adding motion
                  just to spruce things up, but doing it in ways that.
                </p>
              </div>
     {/* Media */}
     <Media />
    </div>
          </div>
        </Layout>
        <HireMe/>
        <div className=' absolute md:bottom-4 bottom-1 right-1 md:right-4 w-24 inline-block'>
          <Image src={Light} alt='light' className='w-20 h-20 md:w-full hidden md:flex md:h-auto'/>
        </div>
      </main>
    </>
  )
}
